# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and Kotlin
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Enable native build optimization
android.ndkVersion=26.1.10909125
